autotools: honor the return value of the comparison tool
This make 'make check' die if the tool does not succeed. Also, ignore the
falure when it's explicitly killed.

diff --git a/contrib/test-scripts/run-bitcoind-for-test.sh.in b/contrib/test-scripts/run-bitcoind-for-test.sh.in
--- a/contrib/test-scripts/run-bitcoind-for-test.sh.in
+++ b/contrib/test-scripts/run-bitcoind-for-test.sh.in
@@ -14,9 +14,14 @@ wait $WAITER
 
 if [ -n "$TIMEOUT" ]; then
   timeout -k 5s "$TIMEOUT"s "$@"
+  RETURN=$?
 else
   "$@"
+  RETURN=$?
 fi
 
 (sleep 15 && kill -0 $BITCOIND 2>/dev/null && kill -9 $BITCOIND $$)&
 kill $BITCOIND && wait $BITCOIND
+
+# timeout returns 124 on timeout, otherwise the return value of the child
+exit $RETURN
